### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by adam-azarchs**
Widen version requirement for `rand` to allow update to 0.8.

Remove reference to marsoc crate.

Return to using published crate for bio, now that 0.35 (and 0.36) has
been released.

Widen version range for nix to permit update to 0.20, as required by
pprof 0.4.3.

Widen version ranges for strum and strum_macros to permit latest
version.

### CODE REVIEW

**Review by DavidBJaffe — COMMENTED** [review]
Cool, thank you!  The change to use of random in the stirling numbers test changes
results and thus breaks a regression test.  Or so it appears.  It would certainly be
better to not change the results, if that's possible.

**Comment by DavidBJaffe** [comment]
If you would like, I can attempt (separately) to update the crates, per what you've done, without
changing results.

**Comment by adam-azarchs** [comment]
The problem there is that the test is using `StdRng`, which isn't stable across versions.  The documentation is quite explicit that if you want results to be stable across versions you should specify which rng algorithm to use.

**Comment by adam-azarchs** [comment]
Actually, while what I said is true and should be fixed, the docs for both 0.7.3 and 0.8.4 say that `StdRng` uses (for now) "ChaCha block cipher with 20 rounds".  So maybe it is due to my change.  The reason I'd changed it that way is because `rng.gen_range` in 0.8 takes only a single argument (a range) while in 0.7 it takes two arguments.  As those are incompatible APIs, I switched to using the distribution instead since that API hasn't changed (and because the docs say that you should be using that anyway if you're sampling repeatedly, as it's more efficient).

Anyway, feel free to add to this PR or do your own thing.  We're all still supposed to be on vacation.  This was me just trying to take a stab at the first step in untangling our dependency tree so we can update `prost`.

**Comment by DavidBJaffe** [comment]
Great -- I am pushing the change separately.  I tried to dig into why the value changed and it hurt
my head.  I decided that since rand is used only in the test, it doesn't matter.

**Pull request closed without merging**
